# 도커 컴포즈 파일을 사용하면 컨테이너 여러 개를 한 번에 실행시킬 수 있고, 컨테이너를 실행시킬 때 옵션을 줄 수 있다.

# 도커 컴포즈 파일 포맷을 최신으로 사용 '3'
version: '3'


services:
  # web이라는 이름의 서비스 하나만 실행
  web:
    # Dockerfile을 을 실행해 컨테이너 이미지를 만든다.
    build: .
    # 서버 실행
    command: python manage.py runserver 0.0.0.0:8000
    # 로컬 컴푸터의 폴더와 도커의 폴더를 연결
    volumes:
      - ./:/usr/app/
    ports:
      - 8000:8000
    # 오류를 보이지 않게 settings.py를 수정, env.dev와 env.prod로 나눠 개발용 파일과 배표용 파일
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=do_it_django_db_user_prod
      - POSTGRES_PASSWORD=do_it_django_db_password_prod
      - POSTGRES_DB=do_it_django_prod

volumes:
  postgres_data:

